name: Release PDF from TeX

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install TeXLive
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full

      - name: Compile TeX to PDF
        run: pdflatex -interaction=nonstopmode Chad_Gauthier_cv_en.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: ChadGauthier_resume_en.pdf

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download PDF artifact
        uses: actions/download-artifact@v4
        with:
          name: pdf
          path: .

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ChadGauthier_resume_en.pdf
          asset_name: ChadGauthier_resume_en.pdf
          asset_content_type: application/pdf