name: Release PDF from TeX

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install TeXLive
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full

      - name: Compile TeX to PDF
        run: pdflatex -interaction=nonstopmode Chad_Gauthier_cv_en.tex Chad_Gauthier_cv_fr.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: |
            Chad_Gauthier_cv_en.pdf
            Chad_Gauthire_cv_fr.pdf

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download PDF artifact
        uses: actions/download-artifact@v4
        with:
          name: pdf
          path: Chad_Gauthier_cv_en.pdf

      - name: Create Release
        id: create_release
        uses: marvinpinto/action-automatic-releases@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          automatic_release_tag: "latest"
          files: |
            Chad_Gauthier_cv_en.pdf
            Chad_Gauthier_cv_fr.pdf